apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gcp-tutorial
  name: gcp-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gcp-tutorial
  template:
    metadata:
      labels:
        run: gcp-tutorial
    spec:
      containers:
      - image: gcp-tutorial
        name: gcp-tutorial
        ports:
        - containerPort: 8080
        imagePullPolicy: Always